##
#  @file
#  Definition of the HTTP status codes.
#
#  @copyright
#  Copyright (c) 2026, Codevenience Organization. All rights reserved.<BR>
#
#  SPDX-License-Identifier: BSD-3-Clause
#
#  @par reference
#  - https://www.rfc-editor.org/rfc/rfc9110.html
##
"""
Definition of HyperText Transfer Protocol (HTTP) status codes.
"""
#
# Section 15.2: Informational 1xx
#
HTTP_STATUS_CONTINUE: int = 100
HTTP_STATUS_SWITCHING_PROTOCOLS: int = 101

#
# Section 15.3: Successful 2xx
#
HTTP_STATUS_OK: int = 200
HTTP_STATUS_CREATED: int = 201
HTTP_STATUS_ACCEPTED: int = 202
HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION: int = 203
HTTP_STATUS_NO_CONTENT: int = 204
HTTP_STATUS_RESET_CONTENT: int = 205
HTTP_STATUS_PARTIAL_CONTENT: int = 206

#
# Section 15.4: Redirection 3xx
#
HTTP_STATUS_MULTIPLE_CHOICES: int = 300
HTTP_STATUS_MOVED_PERMANENTLY: int = 301
HTTP_STATUS_FOUND: int = 302
HTTP_STATUS_SEE_OTHER: int = 303
HTTP_STATUS_NOT_MODIFIED: int = 304
HTTP_STATUS_USE_PROXY: int = 305
HTTP_STATUS_306_UNUSED: int = 306
HTTP_STATUS_TEMPORARY_REDIRECT: int = 307
HTTP_STATUS_PERMANENT_REDIRECT: int = 308

#
# Section 15.5: Client Error 4xx
#
HTTP_STATUS_BAD_REQUEST: int = 400
HTTP_STATUS_UNAUTHORIZED: int = 401
HTTP_STATUS_PAYMENT_REQUIRED: int = 402
HTTP_STATUS_FORBIDDEN: int = 403
HTTP_STATUS_NOT_FOUND: int = 404
HTTP_STATUS_METHOD_NOT_ALLOWED: int = 405
HTTP_STATUS_NOT_ACCEPTABLE: int = 406
HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED: int = 407
HTTP_STATUS_REQUEST_TIMEOUT: int = 408
HTTP_STATUS_CONFLICT: int = 409
HTTP_STATUS_GONE: int = 410
HTTP_STATUS_LENGTH_REQUIRED: int = 411
HTTP_STATUS_PRECONDITION_FAILED: int = 412
HTTP_STATUS_CONTENT_TOO_LARGE: int = 413
HTTP_STATUS_URI_TOO_LONG: int = 414
HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE: int = 415
HTTP_STATUS_RANGE_NOT_SATISFIABLE: int = 416
HTTP_STATUS_EXPECTATION_FAILED: int = 417
HTTP_STATUS_418_UNUSED: int = 418
HTTP_STATUS_MISDIRECTED_REQUEST: int = 421
HTTP_STATUS_UNPROCESSABLE_CONTENT: int = 422
HTTP_STATUS_UPGRADE_REQUIRED: int = 426

#
# Section 15.6: Server Error 5xx
#
HTTP_STATUS_INTERNAL_SERVER_ERROR: int = 500
HTTP_STATUS_NOT_IMPLEMENTED: int = 501
HTTP_STATUS_BAD_GATEWAY: int = 502
HTTP_STATUS_SERVICE_UNAVAILABLE: int = 503
HTTP_STATUS_GATEWAY_TIMEOUT: int = 504
HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED: int = 505
